[workspace]

members = [
    "./tiny/*", "project",
]

[workspace.dependencies]
anyhow = "1.0.86"
ssh2 = "0.9.5"
clap = { version = "4.5.31", features = [ "derive" ] }
flate2 = "1.0.32"
hex = "0.4.3"
sha1 = "0.10.6"
