[package]
name = "tiny-git"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
ssh2.workspace = true
clap.workspace = true
flate2.workspace = true
hex.workspace = true
sha1.workspace = true
